# BMI Triaging
BMI_GREEN_MIN = 17
BMI_GREEN_MAX = 25
BMI_YELLOW_MIN = 25
BMI_YELLOW_MAX = 30
BMI_ORANGE_MIN = 30
BMI_ORANGE_MAX = 35
BMI_RED_MIN = 35
BMI_RED_MAX = 45
# WAIST/HIP RATIO Triaging
WAIST_HIP_RATIO_GREEN_MIN = 0.70
WAIST_HIP_RATIO_GREEN_MAX = 0.90
WAIST_HIP_RATIO_YELLOW_MIN = 0.90
WAIST_HIP_RATIO_YELLOW_MAX = 1

#BODY TEMPERATURE Triaging
TEMPERATURE_GREEN_MIN = 33
TEMPERATURE_GREEN_MAX = 37
TEMPERATURE_YELLOW_MIN = 37
TEMPERATURE_YELLOW_MAX = 37.5
TEMPERATURE_ORANGE_MIN = 37.5
TEMPERATURE_ORANGE_MAX = 38
TEMPERATURE_RED_MIN = 38
TEMPERATURE_RED_MAX = 42

#SPO2 Triaging
SPO2_GREEN_MIN = 96
SPO2_GREEN_MAX = 100
SPO2_YELLOW_MIN = 93
SPO2_YELLOW_MAX = 96
SPO2_ORANGE_MIN = 90
SPO2_ORANGE_MAX = 93
SPO2_RED_MIN = 90
SPO2_RED_MAX = 85

# BP sys Triaging
BP_SYS_GREEN_MIN = 95
BP_SYS_GREEN_MAX = 130
BP_SYS_YELLOW_MIN = 130
BP_SYS_YELLOW_MAX = 140
BP_SYS_ORANGE_MIN = 140
BP_SYS_ORANGE_MAX = 180
BP_SYS_RED_MIN = 180
BP_SYS_RED_MAX = 200

# BP dia Triaging
BP_DIA_GREEN_MIN = 75
BP_DIA_GREEN_MAX = 85
BP_DIA_YELLOW_MIN = 85
BP_DIA_YELLOW_MAX = 90
BP_DIA_ORANGE_MIN = 90
BP_DIA_ORANGE_MAX = 110
BP_DIA_RED_MIN = 110
BP_DIA_RED_MAX = 120


# Blood Sugar Triaging
BLOOD_SUGAR_GREEN_MIN = 3
BLOOD_SUGAR_GREEN_MAX = 7.78
BLOOD_SUGAR_YELLOW_MIN = 7.78
BLOOD_SUGAR_YELLOW_MAX = 11.11
BLOOD_SUGAR_ORANGE_MIN = 11.11
BLOOD_SUGAR_ORANGE_MAX = 16.67
BLOOD_SUGAR_RED_MIN = 16.67
BLOOD_SUGAR_RED_MAX = 30

# Blood HEMOGLOBIN Triaging
BLOOD_HEMOGLOBIN_GREEN_MIN = 18
BLOOD_HEMOGLOBIN_GREEN_MAX = 12
BLOOD_HEMOGLOBIN_YELLOW_MIN = 12
BLOOD_HEMOGLOBIN_YELLOW_MAX = 10
BLOOD_HEMOGLOBIN_ORANGE_MIN = 10
BLOOD_HEMOGLOBIN_ORANGE_MAX = 8
BLOOD_HEMOGLOBIN_RED_MIN = 8
BLOOD_HEMOGLOBIN_RED_MAX = 6

# Pulse Rate Triaging
Pulse_Rate_GREEN_MIN = 60
Pulse_Rate_GREEN_MAX = 100
Pulse_Rate_YELLOW_MIN_1 = 50
Pulse_Rate_YELLOW_MAX_1 = 60
Pulse_Rate_YELLOW_MIN_2 = 100
Pulse_Rate_YELLOW_MAX_2 = 120
Pulse_Rate_ORANGE_MIN_1 = 20
Pulse_Rate_ORANGE_MIN_2 = 50
Pulse_Rate_ORANGE_MAX = 120
Pulse_Rate_RED_MIN = 130
Pulse_Rate_RED_MAX = 150

# Blood Cholesterol Triaging
Blood_Cholesterol_GREEN_MIN = 120
Blood_Cholesterol_GREEN_MAX = 200
Blood_Cholesterol_YELLOW_MIN = 200
Blood_Cholesterol_YELLOW_MAX = 225
Blood_Cholesterol_ORANGE_MIN = 225
Blood_Cholesterol_ORANGE_MAX = 240
Blood_Cholesterol_RED_MIN = 240
Blood_Cholesterol_RED_MAX = 300

# Blood Uric Acid Triaging
Blood_Uric_Acid_GREEN_MIN = 2.5
Blood_Uric_Acid_GREEN_MAX = 7
Blood_Uric_Acid_ORANGE_MIN = 7
Blood_Uric_Acid_ORANGE_MAX = 8
Blood_Uric_Acid_RED_MIN = 8
Blood_Uric_Acid_RED_MAX = 16


# diffent possible colors
RED = "red"
ORANGE = "orange"
YELLOW = "yellow"
GREEN = "green"